#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

// PROGRAM TANK_AUTO
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_LOCATED(BOOL,I_PBFILL)
  __DECLARE_LOCATED(BOOL,I_PBDISCHARGE)
  __DECLARE_LOCATED(INT,I_LEVEL_METER)
  __DECLARE_LOCATED(BOOL,I_MODESELECTOR)
  __DECLARE_LOCATED(INT,Q_FILL_VALVE)
  __DECLARE_LOCATED(INT,Q_DISCHARGE_VALVE)
  __DECLARE_LOCATED(INT,Q_DISPLAY)
  __DECLARE_LOCATED(BOOL,Q_FILL_LIGHT)
  __DECLARE_LOCATED(BOOL,Q_DISCHARGE_LIGHT)
  __DECLARE_LOCATED(INT,LOWSETPOINT)
  __DECLARE_LOCATED(INT,HIGHSETPOINT)
  __DECLARE_LOCATED(INT,TANKLEVEL)

} TANK_AUTO;

void TANK_AUTO_init__(TANK_AUTO *data__, BOOL retain);
// Code part
void TANK_AUTO_body__(TANK_AUTO *data__);
#endif //__POUS_H
