void BASE_PRODUCTION_init__(BASE_PRODUCTION *data__, BOOL retain) {
  __INIT_LOCATED(BOOL,__IX101_0,data__->BASESENTRY,retain)
  __INIT_LOCATED_VALUE(data__->BASESENTRY,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX101_1,data__->BASESEXIT,retain)
  __INIT_LOCATED_VALUE(data__->BASESEXIT,__BOOL_LITERAL(FALSE))
  __INIT_EXTERNAL(BOOL,BASESCENTERBUSY,data__->BASESCENTERBUSY,retain)
  __INIT_EXTERNAL(BOOL,LIDSCENTERBUSY,data__->LIDSCENTERBUSY,retain)
  __INIT_LOCATED(BOOL,__IX101_3,data__->BASESCENTERERROR,retain)
  __INIT_LOCATED_VALUE(data__->BASESCENTERERROR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX101_0,data__->BASESCENTERSTOP,retain)
  __INIT_LOCATED_VALUE(data__->BASESCENTERSTOP,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX101_1,data__->BASESCENTERSTART,retain)
  __INIT_LOCATED_VALUE(data__->BASESCENTERSTART,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX101_2,data__->BASESCENTERRESET,retain)
  __INIT_LOCATED_VALUE(data__->BASESCENTERRESET,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX101_3,data__->BASESRAWCONVEYOR,retain)
  __INIT_LOCATED_VALUE(data__->BASESRAWCONVEYOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX101_4,data__->BASESEXITCONVEYOR,retain)
  __INIT_LOCATED_VALUE(data__->BASESEXITCONVEYOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX101_5,data__->BASESEMITTER,retain)
  __INIT_LOCATED_VALUE(data__->BASESEMITTER,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX101_6,data__->BELTCONV5,retain)
  __INIT_LOCATED_VALUE(data__->BELTCONV5,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX101_7,data__->BELTCONV6,retain)
  __INIT_LOCATED_VALUE(data__->BELTCONV6,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX102_7,data__->EXITCONV,retain)
  __INIT_LOCATED_VALUE(data__->EXITCONV,__BOOL_LITERAL(FALSE))
  __INIT_EXTERNAL(BOOL,FACTORYIORUNNING,data__->FACTORYIORUNNING,retain)
  R_TRIG_init__(&data__->R_TRIG0,retain);
  RS_init__(&data__->RS0,retain);
  __INIT_LOCATED(INT,__QW101,data__->BASESEXITCOUNTER,retain)
  __INIT_LOCATED_VALUE(data__->BASESEXITCOUNTER,0)
  CTU_init__(&data__->CTU0,retain);
  __INIT_EXTERNAL(INT,SCADASETPRODUCTCOUNT,data__->SCADASETPRODUCTCOUNT,retain)
  __INIT_EXTERNAL(INT,ASSEMBLEDPRODUCTCOUNT,data__->ASSEMBLEDPRODUCTCOUNT,retain)
  __INIT_VAR(data__->STOPBASEPRODUCTION,__BOOL_LITERAL(FALSE),retain)
  __INIT_EXTERNAL(BOOL,ESTOPGLOBAL,data__->ESTOPGLOBAL,retain)
  R_TRIG_init__(&data__->R_TRIG1,retain);
  __INIT_VAR(data__->LT37_OUT,__BOOL_LITERAL(FALSE),retain)
}

// Code part
void BASE_PRODUCTION_body__(BASE_PRODUCTION *data__) {
  // Initialise TEMP variables

  __SET_LOCATED(data__->,BASESEMITTER,,((__GET_VAR(data__->STOPBASEPRODUCTION,) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  __SET_LOCATED(data__->,BASESEXITCONVEYOR,,(__GET_EXTERNAL(data__->FACTORYIORUNNING,) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  __SET_LOCATED(data__->,BASESCENTERSTART,,__GET_LOCATED(data__->BASESENTRY,));
  __SET_VAR(data__->R_TRIG0.,CLK,,__GET_LOCATED(data__->BASESCENTERERROR,));
  R_TRIG_body__(&data__->R_TRIG0);
  __SET_LOCATED(data__->,BASESCENTERSTOP,,(__GET_EXTERNAL(data__->ESTOPGLOBAL,) || __GET_VAR(data__->R_TRIG0.Q,)));
  __SET_VAR(data__->RS0.,S,,((((!(__GET_EXTERNAL(data__->LIDSCENTERBUSY,)) && !(__GET_EXTERNAL(data__->BASESCENTERBUSY,))) && !(__GET_LOCATED(data__->BASESCENTERERROR,))) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  __SET_VAR(data__->RS0.,R1,,((__GET_EXTERNAL(data__->BASESCENTERBUSY,) || __GET_LOCATED(data__->BASESCENTERERROR,)) || __GET_EXTERNAL(data__->ESTOPGLOBAL,)));
  RS_body__(&data__->RS0);
  __SET_LOCATED(data__->,BASESRAWCONVEYOR,,__GET_VAR(data__->RS0.Q1,));
  __SET_LOCATED(data__->,BELTCONV5,,(__GET_EXTERNAL(data__->FACTORYIORUNNING,) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  __SET_LOCATED(data__->,BELTCONV6,,(__GET_EXTERNAL(data__->FACTORYIORUNNING,) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  __SET_LOCATED(data__->,EXITCONV,,(__GET_EXTERNAL(data__->FACTORYIORUNNING,) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  __SET_VAR(data__->R_TRIG1.,CLK,,__GET_LOCATED(data__->BASESEXIT,));
  R_TRIG_body__(&data__->R_TRIG1);
  __SET_VAR(data__->CTU0.,CU,,__GET_VAR(data__->R_TRIG1.Q,));
  __SET_VAR(data__->CTU0.,R,,!(__GET_EXTERNAL(data__->FACTORYIORUNNING,)));
  __SET_VAR(data__->CTU0.,PV,,100);
  CTU_body__(&data__->CTU0);
  __SET_LOCATED(data__->,BASESEXITCOUNTER,,__GET_VAR(data__->CTU0.CV,));
  __SET_VAR(data__->,LT37_OUT,,LT__BOOL__INT(
    (BOOL)__BOOL_LITERAL(TRUE),
    NULL,
    (UINT)2,
    (INT)__GET_LOCATED(data__->BASESEXITCOUNTER,),
    (INT)__GET_EXTERNAL(data__->SCADASETPRODUCTCOUNT,)));
  __SET_VAR(data__->,STOPBASEPRODUCTION,,__GET_VAR(data__->LT37_OUT,));

  goto __end;

__end:
  return;
} // BASE_PRODUCTION_body__() 





void ASSEMBLY_init__(ASSEMBLY *data__, BOOL retain) {
  __INIT_EXTERNAL(BOOL,FACTORYIORUNNING,data__->FACTORYIORUNNING,retain)
  __INIT_EXTERNAL(BOOL,ASSEMBLYESTOP2,data__->ASSEMBLYESTOP2,retain)
  __INIT_EXTERNAL(BOOL,ESTOPGLOBAL,data__->ESTOPGLOBAL,retain)
  __INIT_EXTERNAL(BOOL,ASSEMBLYSTARTPB3,data__->ASSEMBLYSTARTPB3,retain)
  __INIT_EXTERNAL(BOOL,ASSEMBLYRESETPB2,data__->ASSEMBLYRESETPB2,retain)
  __INIT_VAR(data__->SCADASTOPLOCAL,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->SCADARESETLOCAL,__BOOL_LITERAL(FALSE),retain)
  __INIT_EXTERNAL(INT,SCADAESTOP,data__->SCADAESTOP,retain)
  __INIT_EXTERNAL(INT,SCADAESTOPRESET,data__->SCADAESTOPRESET,retain)
  __INIT_LOCATED(BOOL,__QX102_0,data__->CONV6M_1_LIDFEEDER,retain)
  __INIT_LOCATED_VALUE(data__->CONV6M_1_LIDFEEDER,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX102_1,data__->CONV6M_4_BASEFEEDER0,retain)
  __INIT_LOCATED_VALUE(data__->CONV6M_4_BASEFEEDER0,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX102_0,data__->DIFFUSESENSOR1,retain)
  __INIT_LOCATED_VALUE(data__->DIFFUSESENSOR1,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX102_1,data__->DIFFUSESENSOR3,retain)
  __INIT_LOCATED_VALUE(data__->DIFFUSESENSOR3,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX102_2,data__->LEFTCLAMPSENSOR,retain)
  __INIT_LOCATED_VALUE(data__->LEFTCLAMPSENSOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX102_3,data__->RIGHTCLAMPSENSOR,retain)
  __INIT_LOCATED_VALUE(data__->RIGHTCLAMPSENSOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX102_2,data__->LEFTCLAMPOUT,retain)
  __INIT_LOCATED_VALUE(data__->LEFTCLAMPOUT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX102_3,data__->RIGHTCLAMPOUT,retain)
  __INIT_LOCATED_VALUE(data__->RIGHTCLAMPOUT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX102_4,data__->Z_AXISDOWNOUT,retain)
  __INIT_LOCATED_VALUE(data__->Z_AXISDOWNOUT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX102_5,data__->X_AXISMOVEOUT,retain)
  __INIT_LOCATED_VALUE(data__->X_AXISMOVEOUT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX102_4,data__->Z_AXISDOWNSENSOR,retain)
  __INIT_LOCATED_VALUE(data__->Z_AXISDOWNSENSOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX102_5,data__->X_AXISMOVESENSOR,retain)
  __INIT_LOCATED_VALUE(data__->X_AXISMOVESENSOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX102_6,data__->GRIPPERONOUT,retain)
  __INIT_LOCATED_VALUE(data__->GRIPPERONOUT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX103_0,data__->CONV4M_5_AFTERRAISE,retain)
  __INIT_LOCATED_VALUE(data__->CONV4M_5_AFTERRAISE,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX103_1,data__->LEFTPOS2_RAISE,retain)
  __INIT_LOCATED_VALUE(data__->LEFTPOS2_RAISE,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX102_6,data__->GRIPPERONSENSOR,retain)
  __INIT_LOCATED_VALUE(data__->GRIPPERONSENSOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX102_7,data__->DIFFUSESENSOR2,retain)
  __INIT_LOCATED_VALUE(data__->DIFFUSESENSOR2,__BOOL_LITERAL(FALSE))
  __INIT_VAR(data__->BEGINASSEMBLY,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->STOPBASEFEEDERCONV,__BOOL_LITERAL(FALSE),retain)
  __INIT_LOCATED(BOOL,__IX104_1,data__->DIFFUSESENSOR7,retain)
  __INIT_LOCATED_VALUE(data__->DIFFUSESENSOR7,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(WORD,__IW100,data__->VISIONSENSOR,retain)
  __INIT_LOCATED_VALUE(data__->VISIONSENSOR,0)
  __INIT_LOCATED(BOOL,__QX104_3,data__->PIVOTBELTRUN,retain)
  __INIT_LOCATED_VALUE(data__->PIVOTBELTRUN,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX104_4,data__->PIVOTBELTTURN,retain)
  __INIT_LOCATED_VALUE(data__->PIVOTBELTTURN,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX104_5,data__->REJECTIONALARM,retain)
  __INIT_LOCATED_VALUE(data__->REJECTIONALARM,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX104_6,data__->REJECTIONSIREN,retain)
  __INIT_LOCATED_VALUE(data__->REJECTIONSIREN,__BOOL_LITERAL(FALSE))
  __INIT_VAR(data__->VISIONTESTFAIL1,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->VISIONTESTFAIL2,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->VISIONTESTFAIL,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->RUNREJECTIONPIVOT,__BOOL_LITERAL(FALSE),retain)
  TON_init__(&data__->TON0,retain);
  __INIT_LOCATED(BOOL,__QX106_3,data__->BELTCONV6M_5,retain)
  __INIT_LOCATED_VALUE(data__->BELTCONV6M_5,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX106_4,data__->BELTCONV6M_6,retain)
  __INIT_LOCATED_VALUE(data__->BELTCONV6M_6,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX106_5,data__->BELTCONV6M_7,retain)
  __INIT_LOCATED_VALUE(data__->BELTCONV6M_7,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX106_6,data__->BELTCONV6M_8,retain)
  __INIT_LOCATED_VALUE(data__->BELTCONV6M_8,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX106_7,data__->CURVEBELTCONV1_CCW,retain)
  __INIT_LOCATED_VALUE(data__->CURVEBELTCONV1_CCW,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX107_0,data__->ASSEMBLYREDLIGHT,retain)
  __INIT_LOCATED_VALUE(data__->ASSEMBLYREDLIGHT,__BOOL_LITERAL(FALSE))
  __INIT_EXTERNAL(INT,ASSEMBLEDPRODUCTCOUNT,data__->ASSEMBLEDPRODUCTCOUNT,retain)
  __INIT_EXTERNAL(INT,QCSTATIONENABLE,data__->QCSTATIONENABLE,retain)
  __INIT_LOCATED(BOOL,__QX107_4,data__->BOOLQCSTATIONENABLE,retain)
  __INIT_LOCATED_VALUE(data__->BOOLQCSTATIONENABLE,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(INT,__QW103,data__->REJECTEDPRODUCTCOUNT,retain)
  __INIT_LOCATED_VALUE(data__->REJECTEDPRODUCTCOUNT,0)
  CTU_init__(&data__->CTU0,retain);
  CTU_init__(&data__->CTU1,retain);
  F_TRIG_init__(&data__->F_TRIG1,retain);
  F_TRIG_init__(&data__->F_TRIG2,retain);
  F_TRIG_init__(&data__->F_TRIG3,retain);
  F_TRIG_init__(&data__->F_TRIG4,retain);
  F_TRIG_init__(&data__->F_TRIG5,retain);
  F_TRIG_init__(&data__->F_TRIG6,retain);
  F_TRIG_init__(&data__->F_TRIG7,retain);
  F_TRIG_init__(&data__->F_TRIG8,retain);
  F_TRIG_init__(&data__->F_TRIG9,retain);
  F_TRIG_init__(&data__->F_TRIG10,retain);
  F_TRIG_init__(&data__->F_TRIG11,retain);
  F_TRIG_init__(&data__->F_TRIG12,retain);
  F_TRIG_init__(&data__->F_TRIG13,retain);
  F_TRIG_init__(&data__->F_TRIG14,retain);
  F_TRIG_init__(&data__->F_TRIG15,retain);
  F_TRIG_init__(&data__->F_TRIG16,retain);
  R_TRIG_init__(&data__->R_TRIG1,retain);
  R_TRIG_init__(&data__->R_TRIG2,retain);
  __INIT_VAR(data__->NE114_OUT,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->NE115_OUT,__BOOL_LITERAL(FALSE),retain)
  R_TRIG_init__(&data__->R_TRIG3,retain);
  R_TRIG_init__(&data__->R_TRIG4,retain);
  __INIT_VAR(data__->EQ203_OUT,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->EQ204_OUT,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->EQ217_OUT,__BOOL_LITERAL(FALSE),retain)
}

// Code part
void ASSEMBLY_body__(ASSEMBLY *data__) {
  // Initialise TEMP variables

  __SET_LOCATED(data__->,CONV6M_1_LIDFEEDER,,(__GET_EXTERNAL(data__->FACTORYIORUNNING,) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  __SET_LOCATED(data__->,CONV6M_4_BASEFEEDER0,,((!(__GET_VAR(data__->STOPBASEFEEDERCONV,)) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  __SET_LOCATED(data__->,CONV4M_5_AFTERRAISE,,(__GET_EXTERNAL(data__->FACTORYIORUNNING,) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  __SET_VAR(data__->F_TRIG1.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR1,));
  F_TRIG_body__(&data__->F_TRIG1);
  if ((__GET_VAR(data__->F_TRIG1.Q,) && __GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,LEFTCLAMPOUT,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG2.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR3,));
  F_TRIG_body__(&data__->F_TRIG2);
  if ((__GET_VAR(data__->F_TRIG2.Q,) && __GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,RIGHTCLAMPOUT,,__BOOL_LITERAL(TRUE));
  };
  if (((!(__GET_VAR(data__->BEGINASSEMBLY,)) && __GET_LOCATED(data__->RIGHTCLAMPOUT,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,Z_AXISDOWNOUT,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG3.,CLK,,__GET_LOCATED(data__->Z_AXISDOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG3);
  if (((__GET_VAR(data__->F_TRIG3.Q,) && __GET_LOCATED(data__->RIGHTCLAMPOUT,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_VAR(data__->,BEGINASSEMBLY,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG4.,CLK,,__GET_LOCATED(data__->Z_AXISDOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG4);
  if (((__GET_VAR(data__->F_TRIG4.Q,) && __GET_LOCATED(data__->RIGHTCLAMPOUT,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,GRIPPERONOUT,,__BOOL_LITERAL(TRUE));
  };
  if ((((__GET_LOCATED(data__->GRIPPERONSENSOR,) && __GET_LOCATED(data__->GRIPPERONOUT,)) && __GET_LOCATED(data__->RIGHTCLAMPOUT,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,Z_AXISDOWNOUT,,__BOOL_LITERAL(FALSE));
  };
  if ((((__GET_LOCATED(data__->GRIPPERONSENSOR,) && __GET_LOCATED(data__->GRIPPERONOUT,)) && __GET_LOCATED(data__->RIGHTCLAMPOUT,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,RIGHTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  if ((((__GET_LOCATED(data__->GRIPPERONSENSOR,) && __GET_LOCATED(data__->GRIPPERONOUT,)) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,X_AXISMOVEOUT,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG5.,CLK,,__GET_LOCATED(data__->X_AXISMOVESENSOR,));
  F_TRIG_body__(&data__->F_TRIG5);
  if ((((((__GET_VAR(data__->F_TRIG5.Q,) && __GET_LOCATED(data__->X_AXISMOVEOUT,)) && __GET_LOCATED(data__->GRIPPERONSENSOR,)) && __GET_LOCATED(data__->GRIPPERONOUT,)) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,Z_AXISDOWNOUT,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG6.,CLK,,__GET_LOCATED(data__->Z_AXISDOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG6);
  if (((((__GET_VAR(data__->F_TRIG6.Q,) && __GET_LOCATED(data__->Z_AXISDOWNOUT,)) && __GET_LOCATED(data__->X_AXISMOVEOUT,)) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,GRIPPERONOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG7.,CLK,,__GET_LOCATED(data__->Z_AXISDOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG7);
  if (((((__GET_VAR(data__->F_TRIG7.Q,) && __GET_LOCATED(data__->Z_AXISDOWNOUT,)) && __GET_LOCATED(data__->X_AXISMOVEOUT,)) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,Z_AXISDOWNOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG8.,CLK,,__GET_LOCATED(data__->Z_AXISDOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG8);
  if (((((__GET_VAR(data__->F_TRIG8.Q,) && __GET_LOCATED(data__->Z_AXISDOWNOUT,)) && __GET_LOCATED(data__->X_AXISMOVEOUT,)) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,X_AXISMOVEOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG9.,CLK,,__GET_LOCATED(data__->Z_AXISDOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG9);
  if ((((((!(__GET_LOCATED(data__->GRIPPERONOUT,)) && __GET_VAR(data__->F_TRIG9.Q,)) && !(__GET_LOCATED(data__->Z_AXISDOWNOUT,))) && __GET_LOCATED(data__->X_AXISMOVEOUT,)) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,LEFTPOS2_RAISE,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG10.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR2,));
  F_TRIG_body__(&data__->F_TRIG10);
  if ((__GET_VAR(data__->F_TRIG10.Q,) && __GET_LOCATED(data__->LEFTPOS2_RAISE,))) {
    __SET_LOCATED(data__->,Z_AXISDOWNOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG11.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR2,));
  F_TRIG_body__(&data__->F_TRIG11);
  if ((__GET_VAR(data__->F_TRIG11.Q,) && __GET_LOCATED(data__->LEFTPOS2_RAISE,))) {
    __SET_LOCATED(data__->,X_AXISMOVEOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG12.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR2,));
  F_TRIG_body__(&data__->F_TRIG12);
  if ((__GET_VAR(data__->F_TRIG12.Q,) && __GET_LOCATED(data__->LEFTPOS2_RAISE,))) {
    __SET_LOCATED(data__->,RIGHTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG13.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR2,));
  F_TRIG_body__(&data__->F_TRIG13);
  if ((__GET_VAR(data__->F_TRIG13.Q,) && __GET_LOCATED(data__->LEFTPOS2_RAISE,))) {
    __SET_LOCATED(data__->,GRIPPERONOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG14.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR2,));
  F_TRIG_body__(&data__->F_TRIG14);
  if ((__GET_VAR(data__->F_TRIG14.Q,) && __GET_LOCATED(data__->LEFTPOS2_RAISE,))) {
    __SET_LOCATED(data__->,LEFTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG15.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR2,));
  F_TRIG_body__(&data__->F_TRIG15);
  if ((__GET_VAR(data__->F_TRIG15.Q,) && __GET_LOCATED(data__->LEFTPOS2_RAISE,))) {
    __SET_VAR(data__->,BEGINASSEMBLY,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG16.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR2,));
  F_TRIG_body__(&data__->F_TRIG16);
  if ((__GET_VAR(data__->F_TRIG16.Q,) && __GET_LOCATED(data__->LEFTPOS2_RAISE,))) {
    __SET_LOCATED(data__->,LEFTPOS2_RAISE,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->R_TRIG1.,CLK,,__GET_VAR(data__->BEGINASSEMBLY,));
  R_TRIG_body__(&data__->R_TRIG1);
  if (__GET_VAR(data__->R_TRIG1.Q,)) {
    __SET_VAR(data__->,STOPBASEFEEDERCONV,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->R_TRIG2.,CLK,,__GET_LOCATED(data__->LEFTPOS2_RAISE,));
  R_TRIG_body__(&data__->R_TRIG2);
  if (__GET_VAR(data__->R_TRIG2.Q,)) {
    __SET_VAR(data__->,STOPBASEFEEDERCONV,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->,NE114_OUT,,NE__BOOL__WORD__WORD(
    (BOOL)__BOOL_LITERAL(TRUE),
    NULL,
    (WORD)__GET_LOCATED(data__->VISIONSENSOR,),
    (WORD)0));
  __SET_VAR(data__->,VISIONTESTFAIL1,,__GET_VAR(data__->NE114_OUT,));
  __SET_VAR(data__->,NE115_OUT,,NE__BOOL__WORD__WORD(
    (BOOL)__BOOL_LITERAL(TRUE),
    NULL,
    (WORD)__GET_LOCATED(data__->VISIONSENSOR,),
    (WORD)2));
  __SET_VAR(data__->,VISIONTESTFAIL2,,__GET_VAR(data__->NE115_OUT,));
  __SET_VAR(data__->,VISIONTESTFAIL,,((__GET_LOCATED(data__->BOOLQCSTATIONENABLE,) && __GET_VAR(data__->VISIONTESTFAIL2,)) && __GET_VAR(data__->VISIONTESTFAIL1,)));
  __SET_VAR(data__->,RUNREJECTIONPIVOT,,((!(__GET_VAR(data__->TON0.Q,)) && !(__GET_LOCATED(data__->DIFFUSESENSOR7,))) && (__GET_VAR(data__->RUNREJECTIONPIVOT,) || __GET_VAR(data__->VISIONTESTFAIL,))));
  __SET_LOCATED(data__->,PIVOTBELTRUN,,__GET_VAR(data__->RUNREJECTIONPIVOT,));
  __SET_LOCATED(data__->,PIVOTBELTTURN,,__GET_VAR(data__->RUNREJECTIONPIVOT,));
  __SET_LOCATED(data__->,REJECTIONALARM,,__GET_VAR(data__->RUNREJECTIONPIVOT,));
  __SET_LOCATED(data__->,REJECTIONSIREN,,__GET_VAR(data__->RUNREJECTIONPIVOT,));
  __SET_LOCATED(data__->,BELTCONV6M_5,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  __SET_LOCATED(data__->,BELTCONV6M_6,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  __SET_LOCATED(data__->,BELTCONV6M_7,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  __SET_LOCATED(data__->,BELTCONV6M_8,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  __SET_LOCATED(data__->,CURVEBELTCONV1_CCW,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,Z_AXISDOWNOUT,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,X_AXISMOVEOUT,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,RIGHTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,GRIPPERONOUT,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,LEFTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_VAR(data__->,BEGINASSEMBLY,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,LEFTPOS2_RAISE,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_VAR(data__->,STOPBASEFEEDERCONV,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->R_TRIG3.,CLK,,__GET_LOCATED(data__->LEFTPOS2_RAISE,));
  R_TRIG_body__(&data__->R_TRIG3);
  __SET_VAR(data__->CTU1.,CU,,__GET_VAR(data__->R_TRIG3.Q,));
  __SET_VAR(data__->CTU1.,R,,!(__GET_EXTERNAL(data__->FACTORYIORUNNING,)));
  __SET_VAR(data__->CTU1.,PV,,100);
  CTU_body__(&data__->CTU1);
  __SET_EXTERNAL(data__->,ASSEMBLEDPRODUCTCOUNT,,__GET_VAR(data__->CTU1.CV,));
  __SET_VAR(data__->R_TRIG4.,CLK,,__GET_VAR(data__->RUNREJECTIONPIVOT,));
  R_TRIG_body__(&data__->R_TRIG4);
  __SET_VAR(data__->CTU0.,CU,,__GET_VAR(data__->R_TRIG4.Q,));
  __SET_VAR(data__->CTU0.,R,,!(__GET_EXTERNAL(data__->FACTORYIORUNNING,)));
  __SET_VAR(data__->CTU0.,PV,,100);
  CTU_body__(&data__->CTU0);
  __SET_LOCATED(data__->,REJECTEDPRODUCTCOUNT,,__GET_VAR(data__->CTU0.CV,));
  __SET_EXTERNAL(data__->,ESTOPGLOBAL,,(!(__GET_VAR(data__->SCADARESETLOCAL,)) && ((!(__GET_EXTERNAL(data__->ASSEMBLYRESETPB2,)) && ((__GET_EXTERNAL(data__->ESTOPGLOBAL,) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)) || (!(__GET_EXTERNAL(data__->ASSEMBLYESTOP2,)) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)))) || (__GET_VAR(data__->SCADASTOPLOCAL,) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)))));
  __SET_LOCATED(data__->,ASSEMBLYREDLIGHT,,__GET_EXTERNAL(data__->ESTOPGLOBAL,));
  __SET_VAR(data__->,EQ203_OUT,,EQ__BOOL__INT(
    (BOOL)__BOOL_LITERAL(TRUE),
    NULL,
    (UINT)2,
    (INT)__GET_EXTERNAL(data__->SCADAESTOP,),
    (INT)9));
  __SET_VAR(data__->,SCADASTOPLOCAL,,__GET_VAR(data__->EQ203_OUT,));
  __SET_VAR(data__->,EQ204_OUT,,EQ__BOOL__INT(
    (BOOL)__BOOL_LITERAL(TRUE),
    NULL,
    (UINT)2,
    (INT)__GET_EXTERNAL(data__->SCADAESTOPRESET,),
    (INT)1));
  __SET_VAR(data__->,SCADARESETLOCAL,,__GET_VAR(data__->EQ204_OUT,));
  __SET_VAR(data__->,EQ217_OUT,,EQ__BOOL__INT(
    (BOOL)__BOOL_LITERAL(TRUE),
    NULL,
    (UINT)2,
    (INT)__GET_EXTERNAL(data__->QCSTATIONENABLE,),
    (INT)1));
  __SET_LOCATED(data__->,BOOLQCSTATIONENABLE,,__GET_VAR(data__->EQ217_OUT,));
  __SET_VAR(data__->TON0.,IN,,__GET_VAR(data__->RUNREJECTIONPIVOT,));
  __SET_VAR(data__->TON0.,PT,,__time_to_timespec(1, 0, 5, 0, 0, 0));
  TON_body__(&data__->TON0);

  goto __end;

__end:
  return;
} // ASSEMBLY_body__() 





static inline INT __WAREHOUSE_MOVE__INT__INT1(BOOL EN,
  INT IN,
  WAREHOUSE *data__)
{
  INT __res;
  BOOL __TMP_ENO = __GET_VAR(data__->MOVE109_ENO,);
  __res = MOVE__INT__INT(EN,
    &__TMP_ENO,
    IN);
  __SET_VAR(,data__->MOVE109_ENO,,__TMP_ENO);
  return __res;
}

void WAREHOUSE_init__(WAREHOUSE *data__, BOOL retain) {
  __INIT_LOCATED(BOOL,__QX104_7,data__->ROLLERCONV2M_1,retain)
  __INIT_LOCATED_VALUE(data__->ROLLERCONV2M_1,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX105_0,data__->ROLLERCONV2M_2,retain)
  __INIT_LOCATED_VALUE(data__->ROLLERCONV2M_2,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX105_1,data__->ROLLERCONV2M_3,retain)
  __INIT_LOCATED_VALUE(data__->ROLLERCONV2M_3,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX105_2,data__->ROLLERCONV2M_4,retain)
  __INIT_LOCATED_VALUE(data__->ROLLERCONV2M_4,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX105_3,data__->ROLLERCONV2M_5,retain)
  __INIT_LOCATED_VALUE(data__->ROLLERCONV2M_5,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX105_4,data__->CURVEROLLER2_CW,retain)
  __INIT_LOCATED_VALUE(data__->CURVEROLLER2_CW,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX105_5,data__->CURVEROLLER1_CCW,retain)
  __INIT_LOCATED_VALUE(data__->CURVEROLLER1_CCW,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX105_6,data__->LOADCONV1,retain)
  __INIT_LOCATED_VALUE(data__->LOADCONV1,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX105_7,data__->LOADCONV2,retain)
  __INIT_LOCATED_VALUE(data__->LOADCONV2,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX106_0,data__->STACKCRANE1_LEFT,retain)
  __INIT_LOCATED_VALUE(data__->STACKCRANE1_LEFT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX106_1,data__->STACKCRANE1_RIGHT,retain)
  __INIT_LOCATED_VALUE(data__->STACKCRANE1_RIGHT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX106_2,data__->STACKCRANE1_LIFT,retain)
  __INIT_LOCATED_VALUE(data__->STACKCRANE1_LIFT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(INT,__QW105,data__->STACKCRANE1_TARGETPOS,retain)
  __INIT_LOCATED_VALUE(data__->STACKCRANE1_TARGETPOS,0)
  __INIT_LOCATED(BOOL,__IX104_2,data__->STACKCRANE1_MOVX,retain)
  __INIT_LOCATED_VALUE(data__->STACKCRANE1_MOVX,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX104_3,data__->STACKCRANE1_MOVZ,retain)
  __INIT_LOCATED_VALUE(data__->STACKCRANE1_MOVZ,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX104_4,data__->STACKCRANE1_LEFTLIMIT,retain)
  __INIT_LOCATED_VALUE(data__->STACKCRANE1_LEFTLIMIT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX104_5,data__->STACKCRANE1_RIGHTLIMIT0,retain)
  __INIT_LOCATED_VALUE(data__->STACKCRANE1_RIGHTLIMIT0,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX104_6,data__->STACKCRANE1_MIDDLELIMIT,retain)
  __INIT_LOCATED_VALUE(data__->STACKCRANE1_MIDDLELIMIT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX104_7,data__->REFLECTIVESENSOR_5,retain)
  __INIT_LOCATED_VALUE(data__->REFLECTIVESENSOR_5,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX105_0,data__->REFLECTIVESENSOR_6,retain)
  __INIT_LOCATED_VALUE(data__->REFLECTIVESENSOR_6,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX105_1,data__->REFLECTIVESENSOR_7,retain)
  __INIT_LOCATED_VALUE(data__->REFLECTIVESENSOR_7,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX105_2,data__->REFLECTIVESENSOR_8,retain)
  __INIT_LOCATED_VALUE(data__->REFLECTIVESENSOR_8,__BOOL_LITERAL(FALSE))
  __INIT_EXTERNAL(BOOL,FACTORYIORUNNING,data__->FACTORYIORUNNING,retain)
  __INIT_VAR(data__->STARTLOADING,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->STARTSTACKING,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->STARTSTACKING2,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->STARTSTACKING3,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->STARTSTACKING4,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->STARTSTACKING5,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->STARTSTACKING6,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->STARTSTACKING7,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->STARTSTACKING8,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->FACTORYIOSTOP,__BOOL_LITERAL(FALSE),retain)
  __INIT_LOCATED(BOOL,__IX105_6,data__->SAFETYDOORSENSOR,retain)
  __INIT_LOCATED_VALUE(data__->SAFETYDOORSENSOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX105_7,data__->SAFETYDOORRESET,retain)
  __INIT_LOCATED_VALUE(data__->SAFETYDOORRESET,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX107_2,data__->SAFETYDOORLIGHT,retain)
  __INIT_LOCATED_VALUE(data__->SAFETYDOORLIGHT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX107_3,data__->SAFETYDOORSIREN,retain)
  __INIT_LOCATED_VALUE(data__->SAFETYDOORSIREN,__BOOL_LITERAL(FALSE))
  __INIT_VAR(data__->TARGETPOSITIONVAR,0,retain)
  CTU_init__(&data__->CTU0,retain);
  F_TRIG_init__(&data__->F_TRIG1,retain);
  F_TRIG_init__(&data__->F_TRIG2,retain);
  F_TRIG_init__(&data__->F_TRIG3,retain);
  R_TRIG_init__(&data__->R_TRIG1,retain);
  __INIT_VAR(data__->SEL60_OUT,0,retain)
  R_TRIG_init__(&data__->R_TRIG2,retain);
  F_TRIG_init__(&data__->F_TRIG4,retain);
  F_TRIG_init__(&data__->F_TRIG5,retain);
  R_TRIG_init__(&data__->R_TRIG3,retain);
  F_TRIG_init__(&data__->F_TRIG6,retain);
  R_TRIG_init__(&data__->R_TRIG4,retain);
  __INIT_VAR(data__->MOVE109_ENO,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->MOVE109_OUT,0,retain)
}

// Code part
void WAREHOUSE_body__(WAREHOUSE *data__) {
  // Initialise TEMP variables

  __SET_LOCATED(data__->,ROLLERCONV2M_3,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  __SET_LOCATED(data__->,ROLLERCONV2M_4,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  __SET_LOCATED(data__->,ROLLERCONV2M_5,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  __SET_LOCATED(data__->,CURVEROLLER2_CW,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  __SET_LOCATED(data__->,CURVEROLLER1_CCW,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  __SET_VAR(data__->F_TRIG1.,CLK,,__GET_LOCATED(data__->REFLECTIVESENSOR_5,));
  F_TRIG_body__(&data__->F_TRIG1);
  __SET_VAR(data__->,STARTLOADING,,((__GET_LOCATED(data__->REFLECTIVESENSOR_6,) && (__GET_VAR(data__->F_TRIG1.Q,) || __GET_VAR(data__->STARTLOADING,))) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)));
  __SET_LOCATED(data__->,ROLLERCONV2M_1,,__GET_VAR(data__->STARTLOADING,));
  __SET_LOCATED(data__->,LOADCONV2,,__GET_VAR(data__->STARTLOADING,));
  __SET_VAR(data__->F_TRIG2.,CLK,,__GET_LOCATED(data__->REFLECTIVESENSOR_6,));
  F_TRIG_body__(&data__->F_TRIG2);
  __SET_VAR(data__->,STARTSTACKING,,((!(__GET_VAR(data__->STARTSTACKING8,)) && (__GET_VAR(data__->F_TRIG2.Q,) || __GET_VAR(data__->STARTSTACKING,))) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)));
  __SET_LOCATED(data__->,STACKCRANE1_LEFT,,(!(__GET_VAR(data__->STARTSTACKING2,)) && __GET_VAR(data__->STARTSTACKING,)));
  __SET_LOCATED(data__->,STACKCRANE1_LIFT,,((!(__GET_VAR(data__->STARTSTACKING6,)) && (__GET_LOCATED(data__->STACKCRANE1_LIFT,) || (__GET_LOCATED(data__->STACKCRANE1_LEFTLIMIT,) && __GET_LOCATED(data__->STACKCRANE1_LEFT,)))) && __GET_VAR(data__->STARTSTACKING,)));
  __SET_VAR(data__->F_TRIG3.,CLK,,__GET_LOCATED(data__->STACKCRANE1_MOVZ,));
  F_TRIG_body__(&data__->F_TRIG3);
  __SET_VAR(data__->,STARTSTACKING2,,(((__GET_VAR(data__->F_TRIG3.Q,) && __GET_LOCATED(data__->STACKCRANE1_LIFT,)) || __GET_VAR(data__->STARTSTACKING2,)) && __GET_VAR(data__->STARTSTACKING,)));
  __SET_VAR(data__->R_TRIG1.,CLK,,__GET_LOCATED(data__->STACKCRANE1_MIDDLELIMIT,));
  R_TRIG_body__(&data__->R_TRIG1);
  __SET_VAR(data__->,STARTSTACKING3,,((__GET_VAR(data__->R_TRIG1.Q,) || __GET_VAR(data__->STARTSTACKING3,)) && __GET_VAR(data__->STARTSTACKING2,)));
  __SET_VAR(data__->,SEL60_OUT,,SEL__INT__BOOL__INT__INT(
    (BOOL)__BOOL_LITERAL(TRUE),
    NULL,
    (BOOL)__GET_VAR(data__->STARTSTACKING3,),
    (INT)55,
    (INT)__GET_VAR(data__->TARGETPOSITIONVAR,)));
  __SET_LOCATED(data__->,STACKCRANE1_TARGETPOS,,__GET_VAR(data__->SEL60_OUT,));
  __SET_VAR(data__->R_TRIG2.,CLK,,__GET_VAR(data__->STARTSTACKING,));
  R_TRIG_body__(&data__->R_TRIG2);
  __SET_VAR(data__->CTU0.,EN,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  __SET_VAR(data__->CTU0.,CU,,__GET_VAR(data__->R_TRIG2.Q,));
  __SET_VAR(data__->CTU0.,R,,__GET_VAR(data__->FACTORYIOSTOP,));
  __SET_VAR(data__->CTU0.,PV,,54);
  CTU_body__(&data__->CTU0);
  if (__GET_VAR(data__->CTU0.ENO,)) {
    __SET_VAR(data__->,TARGETPOSITIONVAR,,__GET_VAR(data__->CTU0.CV,));
  };
  __SET_VAR(data__->F_TRIG4.,CLK,,__GET_LOCATED(data__->STACKCRANE1_MOVX,));
  F_TRIG_body__(&data__->F_TRIG4);
  __SET_VAR(data__->,STARTSTACKING4,,((__GET_VAR(data__->F_TRIG4.Q,) || __GET_VAR(data__->STARTSTACKING4,)) && __GET_VAR(data__->STARTSTACKING3,)));
  __SET_VAR(data__->F_TRIG5.,CLK,,__GET_LOCATED(data__->STACKCRANE1_MOVZ,));
  F_TRIG_body__(&data__->F_TRIG5);
  __SET_VAR(data__->,STARTSTACKING5,,((__GET_VAR(data__->F_TRIG5.Q,) || __GET_VAR(data__->STARTSTACKING5,)) && __GET_VAR(data__->STARTSTACKING3,)));
  __SET_LOCATED(data__->,STACKCRANE1_RIGHT,,((!(__GET_VAR(data__->STARTSTACKING7,)) && __GET_VAR(data__->STARTSTACKING5,)) && __GET_VAR(data__->STARTSTACKING4,)));
  __SET_VAR(data__->R_TRIG3.,CLK,,__GET_LOCATED(data__->STACKCRANE1_RIGHTLIMIT0,));
  R_TRIG_body__(&data__->R_TRIG3);
  __SET_VAR(data__->,STARTSTACKING6,,(((__GET_VAR(data__->R_TRIG3.Q,) || __GET_VAR(data__->STARTSTACKING6,)) && __GET_VAR(data__->STARTSTACKING5,)) && __GET_VAR(data__->STARTSTACKING4,)));
  __SET_VAR(data__->F_TRIG6.,CLK,,__GET_LOCATED(data__->STACKCRANE1_MOVZ,));
  F_TRIG_body__(&data__->F_TRIG6);
  __SET_VAR(data__->,STARTSTACKING7,,((__GET_VAR(data__->F_TRIG6.Q,) || __GET_VAR(data__->STARTSTACKING7,)) && __GET_VAR(data__->STARTSTACKING6,)));
  __SET_VAR(data__->R_TRIG4.,CLK,,__GET_LOCATED(data__->STACKCRANE1_MIDDLELIMIT,));
  R_TRIG_body__(&data__->R_TRIG4);
  __SET_VAR(data__->,STARTSTACKING8,,((__GET_VAR(data__->R_TRIG4.Q,) || __GET_VAR(data__->STARTSTACKING8,)) && __GET_VAR(data__->STARTSTACKING7,)));
  __SET_VAR(data__->,MOVE109_OUT,,__WAREHOUSE_MOVE__INT__INT1(
    (BOOL)!(__GET_EXTERNAL(data__->FACTORYIORUNNING,)),
    (INT)0,
    data__));
  if (__GET_VAR(data__->MOVE109_ENO,)) {
    __SET_VAR(data__->,TARGETPOSITIONVAR,,__GET_VAR(data__->MOVE109_OUT,));
  };
  __SET_VAR(data__->,FACTORYIOSTOP,,!(__GET_EXTERNAL(data__->FACTORYIORUNNING,)));
  __SET_LOCATED(data__->,SAFETYDOORSIREN,,((!(__GET_LOCATED(data__->SAFETYDOORRESET,)) && (!(__GET_LOCATED(data__->SAFETYDOORSENSOR,)) || __GET_LOCATED(data__->SAFETYDOORSIREN,))) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)));
  __SET_LOCATED(data__->,SAFETYDOORLIGHT,,((!(__GET_LOCATED(data__->SAFETYDOORRESET,)) && (!(__GET_LOCATED(data__->SAFETYDOORSENSOR,)) || __GET_LOCATED(data__->SAFETYDOORSIREN,))) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)));

  goto __end;

__end:
  return;
} // WAREHOUSE_body__() 





void LIDS_PRODUCTION_init__(LIDS_PRODUCTION *data__, BOOL retain) {
  __INIT_LOCATED(BOOL,__IX100_0,data__->LIDSENTRY,retain)
  __INIT_LOCATED_VALUE(data__->LIDSENTRY,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX100_1,data__->LIDSEXIT,retain)
  __INIT_LOCATED_VALUE(data__->LIDSEXIT,__BOOL_LITERAL(FALSE))
  __INIT_EXTERNAL(BOOL,LIDSCENTERBUSY,data__->LIDSCENTERBUSY,retain)
  __INIT_EXTERNAL(BOOL,BASESCENTERBUSY,data__->BASESCENTERBUSY,retain)
  __INIT_LOCATED(BOOL,__IX100_3,data__->LIDSCENTERERROR,retain)
  __INIT_LOCATED_VALUE(data__->LIDSCENTERERROR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX100_0,data__->LIDSCENTERSTOP,retain)
  __INIT_LOCATED_VALUE(data__->LIDSCENTERSTOP,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX100_1,data__->LIDSCENTERSTART,retain)
  __INIT_LOCATED_VALUE(data__->LIDSCENTERSTART,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX100_2,data__->LIDSCENTERPRODUCE,retain)
  __INIT_LOCATED_VALUE(data__->LIDSCENTERPRODUCE,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX100_3,data__->LIDSRAWCONVEYOR,retain)
  __INIT_LOCATED_VALUE(data__->LIDSRAWCONVEYOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX100_4,data__->LIDSEXITCONVEYOR,retain)
  __INIT_LOCATED_VALUE(data__->LIDSEXITCONVEYOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX100_7,data__->LIDSEXITCONVEYOR2,retain)
  __INIT_LOCATED_VALUE(data__->LIDSEXITCONVEYOR2,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX100_5,data__->LIDSEMITTER,retain)
  __INIT_LOCATED_VALUE(data__->LIDSEMITTER,__BOOL_LITERAL(FALSE))
  __INIT_EXTERNAL(BOOL,FACTORYIORUN,data__->FACTORYIORUN,retain)
  __INIT_EXTERNAL(BOOL,FACTORYIORUNNING,data__->FACTORYIORUNNING,retain)
  R_TRIG_init__(&data__->R_TRIG0,retain);
  RS_init__(&data__->RS0,retain);
  CTU_init__(&data__->CTU0,retain);
  __INIT_LOCATED(INT,__QW100,data__->LIDSEXITCOUNTER,retain)
  __INIT_LOCATED_VALUE(data__->LIDSEXITCOUNTER,0)
  __INIT_LOCATED(BOOL,__IX100_5,data__->STARTBUTTON2,retain)
  __INIT_LOCATED_VALUE(data__->STARTBUTTON2,__BOOL_LITERAL(FALSE))
  __INIT_EXTERNAL(INT,SCADASETPRODUCTCOUNT,data__->SCADASETPRODUCTCOUNT,retain)
  __INIT_EXTERNAL(INT,ASSEMBLEDPRODUCTCOUNT,data__->ASSEMBLEDPRODUCTCOUNT,retain)
  __INIT_EXTERNAL(INT,SCADAFACTORYIOSTART,data__->SCADAFACTORYIOSTART,retain)
  __INIT_VAR(data__->STOPLIDPRODUCTION,__BOOL_LITERAL(FALSE),retain)
  __INIT_EXTERNAL(BOOL,ESTOPGLOBAL,data__->ESTOPGLOBAL,retain)
  R_TRIG_init__(&data__->R_TRIG1,retain);
  __INIT_VAR(data__->LT37_OUT,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->EQ43_OUT,__BOOL_LITERAL(FALSE),retain)
}

// Code part
void LIDS_PRODUCTION_body__(LIDS_PRODUCTION *data__) {
  // Initialise TEMP variables

  __SET_LOCATED(data__->,LIDSEMITTER,,((__GET_VAR(data__->STOPLIDPRODUCTION,) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  __SET_LOCATED(data__->,LIDSEXITCONVEYOR,,(__GET_EXTERNAL(data__->FACTORYIORUNNING,) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  if ((__GET_EXTERNAL(data__->FACTORYIORUNNING,) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,)))) {
    __SET_LOCATED(data__->,LIDSCENTERPRODUCE,,__BOOL_LITERAL(TRUE));
  };
  __SET_LOCATED(data__->,LIDSCENTERSTART,,__GET_LOCATED(data__->LIDSENTRY,));
  __SET_VAR(data__->R_TRIG0.,CLK,,__GET_LOCATED(data__->LIDSCENTERERROR,));
  R_TRIG_body__(&data__->R_TRIG0);
  __SET_LOCATED(data__->,LIDSCENTERSTOP,,(__GET_EXTERNAL(data__->ESTOPGLOBAL,) || __GET_VAR(data__->R_TRIG0.Q,)));
  __SET_VAR(data__->RS0.,S,,((((!(__GET_EXTERNAL(data__->BASESCENTERBUSY,)) && !(__GET_EXTERNAL(data__->LIDSCENTERBUSY,))) && !(__GET_LOCATED(data__->LIDSCENTERERROR,))) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  __SET_VAR(data__->RS0.,R1,,((__GET_EXTERNAL(data__->ESTOPGLOBAL,) || __GET_EXTERNAL(data__->LIDSCENTERBUSY,)) || __GET_LOCATED(data__->LIDSCENTERERROR,)));
  RS_body__(&data__->RS0);
  __SET_LOCATED(data__->,LIDSRAWCONVEYOR,,__GET_VAR(data__->RS0.Q1,));
  __SET_LOCATED(data__->,LIDSEXITCONVEYOR2,,(__GET_EXTERNAL(data__->FACTORYIORUNNING,) && !(__GET_EXTERNAL(data__->ESTOPGLOBAL,))));
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,LIDSCENTERPRODUCE,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->R_TRIG1.,CLK,,__GET_LOCATED(data__->LIDSEXIT,));
  R_TRIG_body__(&data__->R_TRIG1);
  __SET_VAR(data__->CTU0.,CU,,__GET_VAR(data__->R_TRIG1.Q,));
  __SET_VAR(data__->CTU0.,R,,!(__GET_EXTERNAL(data__->FACTORYIORUNNING,)));
  __SET_VAR(data__->CTU0.,PV,,100);
  CTU_body__(&data__->CTU0);
  __SET_LOCATED(data__->,LIDSEXITCOUNTER,,__GET_VAR(data__->CTU0.CV,));
  __SET_VAR(data__->,LT37_OUT,,LT__BOOL__INT(
    (BOOL)__BOOL_LITERAL(TRUE),
    NULL,
    (UINT)2,
    (INT)__GET_LOCATED(data__->LIDSEXITCOUNTER,),
    (INT)__GET_EXTERNAL(data__->SCADASETPRODUCTCOUNT,)));
  __SET_VAR(data__->,STOPLIDPRODUCTION,,__GET_VAR(data__->LT37_OUT,));
  __SET_VAR(data__->,EQ43_OUT,,EQ__BOOL__INT(
    (BOOL)__BOOL_LITERAL(TRUE),
    NULL,
    (UINT)2,
    (INT)__GET_EXTERNAL(data__->SCADAFACTORYIOSTART,),
    (INT)1));
  __SET_EXTERNAL(data__->,FACTORYIORUN,,__GET_VAR(data__->EQ43_OUT,));

  goto __end;

__end:
  return;
} // LIDS_PRODUCTION_body__() 





void PALLETIZER_init__(PALLETIZER *data__, BOOL retain) {
  __INIT_EXTERNAL(BOOL,FACTORYIORUNNING,data__->FACTORYIORUNNING,retain)
  __INIT_LOCATED(BOOL,__QX103_2,data__->CONV6M_2_STACKFEEDER,retain)
  __INIT_LOCATED_VALUE(data__->CONV6M_2_STACKFEEDER,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX103_3,data__->CONV6M_3_AFTERSTACK,retain)
  __INIT_LOCATED_VALUE(data__->CONV6M_3_AFTERSTACK,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX103_0,data__->DIFFUSESENSOR5,retain)
  __INIT_LOCATED_VALUE(data__->DIFFUSESENSOR5,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX103_1,data__->DIFFUSESENSOR4,retain)
  __INIT_LOCATED_VALUE(data__->DIFFUSESENSOR4,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX103_2,data__->LEFTCLAMPSENSOR,retain)
  __INIT_LOCATED_VALUE(data__->LEFTCLAMPSENSOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX103_3,data__->RIGHTCLAMPSENSOR,retain)
  __INIT_LOCATED_VALUE(data__->RIGHTCLAMPSENSOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX103_4,data__->LEFTCLAMPOUT,retain)
  __INIT_LOCATED_VALUE(data__->LEFTCLAMPOUT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX103_5,data__->RIGHTCLAMPOUT,retain)
  __INIT_LOCATED_VALUE(data__->RIGHTCLAMPOUT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX103_6,data__->Z_AXIS2DOWNOUT,retain)
  __INIT_LOCATED_VALUE(data__->Z_AXIS2DOWNOUT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX103_7,data__->X_AXIS2MOVEOUT,retain)
  __INIT_LOCATED_VALUE(data__->X_AXIS2MOVEOUT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX103_4,data__->Z_AXIS2DOWNSENSOR,retain)
  __INIT_LOCATED_VALUE(data__->Z_AXIS2DOWNSENSOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX103_5,data__->X_AXIS2MOVESENSOR,retain)
  __INIT_LOCATED_VALUE(data__->X_AXIS2MOVESENSOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX104_0,data__->GRIPPER2ONOUT,retain)
  __INIT_LOCATED_VALUE(data__->GRIPPER2ONOUT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX104_1,data__->LEFTPOS4_RAISE,retain)
  __INIT_LOCATED_VALUE(data__->LEFTPOS4_RAISE,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX104_2,data__->STACKEMITTER,retain)
  __INIT_LOCATED_VALUE(data__->STACKEMITTER,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX103_6,data__->GRIPPER2ONSENSOR,retain)
  __INIT_LOCATED_VALUE(data__->GRIPPER2ONSENSOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX103_7,data__->DIFFUSESENSOR6,retain)
  __INIT_LOCATED_VALUE(data__->DIFFUSESENSOR6,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX104_0,data__->RIGHTPOS1CLAMPOFF,retain)
  __INIT_LOCATED_VALUE(data__->RIGHTPOS1CLAMPOFF,__BOOL_LITERAL(FALSE))
  __INIT_VAR(data__->BEGINASSEMBLY,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->STOPFEEDERCONVEYOR,__BOOL_LITERAL(FALSE),retain)
  __INIT_VAR(data__->PICKUPFORSTACK,__BOOL_LITERAL(FALSE),retain)
  CTU_init__(&data__->CTU0,retain);
  __INIT_LOCATED(INT,__QW104,data__->CRATEDPRODUCTCOUNT,retain)
  __INIT_LOCATED_VALUE(data__->CRATEDPRODUCTCOUNT,0)
  F_TRIG_init__(&data__->F_TRIG1,retain);
  F_TRIG_init__(&data__->F_TRIG2,retain);
  F_TRIG_init__(&data__->F_TRIG3,retain);
  F_TRIG_init__(&data__->F_TRIG4,retain);
  F_TRIG_init__(&data__->F_TRIG5,retain);
  F_TRIG_init__(&data__->F_TRIG6,retain);
  F_TRIG_init__(&data__->F_TRIG7,retain);
  F_TRIG_init__(&data__->F_TRIG8,retain);
  F_TRIG_init__(&data__->F_TRIG9,retain);
  F_TRIG_init__(&data__->F_TRIG10,retain);
  F_TRIG_init__(&data__->F_TRIG11,retain);
  F_TRIG_init__(&data__->F_TRIG12,retain);
  F_TRIG_init__(&data__->F_TRIG13,retain);
  F_TRIG_init__(&data__->F_TRIG14,retain);
  F_TRIG_init__(&data__->F_TRIG15,retain);
  F_TRIG_init__(&data__->F_TRIG16,retain);
  F_TRIG_init__(&data__->F_TRIG17,retain);
  F_TRIG_init__(&data__->F_TRIG18,retain);
  F_TRIG_init__(&data__->F_TRIG19,retain);
  F_TRIG_init__(&data__->F_TRIG20,retain);
  F_TRIG_init__(&data__->F_TRIG21,retain);
  F_TRIG_init__(&data__->F_TRIG22,retain);
  R_TRIG_init__(&data__->R_TRIG1,retain);
  R_TRIG_init__(&data__->R_TRIG2,retain);
}

// Code part
void PALLETIZER_body__(PALLETIZER *data__) {
  // Initialise TEMP variables

  __SET_LOCATED(data__->,CONV6M_2_STACKFEEDER,,(!(__GET_VAR(data__->STOPFEEDERCONVEYOR,)) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)));
  __SET_LOCATED(data__->,CONV6M_3_AFTERSTACK,,__GET_EXTERNAL(data__->FACTORYIORUNNING,));
  __SET_VAR(data__->F_TRIG1.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR5,));
  F_TRIG_body__(&data__->F_TRIG1);
  if ((__GET_VAR(data__->F_TRIG1.Q,) && __GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,LEFTCLAMPOUT,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG2.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR4,));
  F_TRIG_body__(&data__->F_TRIG2);
  if ((__GET_VAR(data__->F_TRIG2.Q,) && __GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,RIGHTCLAMPOUT,,__BOOL_LITERAL(TRUE));
  };
  if (((!(__GET_VAR(data__->BEGINASSEMBLY,)) && __GET_LOCATED(data__->RIGHTCLAMPOUT,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,X_AXIS2MOVEOUT,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG3.,CLK,,__GET_LOCATED(data__->X_AXIS2MOVESENSOR,));
  F_TRIG_body__(&data__->F_TRIG3);
  if (((((__GET_VAR(data__->F_TRIG3.Q,) && __GET_LOCATED(data__->X_AXIS2MOVEOUT,)) && !(__GET_VAR(data__->BEGINASSEMBLY,))) && __GET_LOCATED(data__->RIGHTCLAMPOUT,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,Z_AXIS2DOWNOUT,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG4.,CLK,,__GET_LOCATED(data__->Z_AXIS2DOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG4);
  if ((((__GET_VAR(data__->F_TRIG4.Q,) && __GET_LOCATED(data__->Z_AXIS2DOWNOUT,)) && __GET_LOCATED(data__->RIGHTCLAMPOUT,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_VAR(data__->,BEGINASSEMBLY,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG5.,CLK,,__GET_LOCATED(data__->Z_AXIS2DOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG5);
  if (((__GET_VAR(data__->F_TRIG5.Q,) && __GET_LOCATED(data__->RIGHTCLAMPOUT,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,GRIPPER2ONOUT,,__BOOL_LITERAL(TRUE));
  };
  if ((((__GET_LOCATED(data__->GRIPPER2ONSENSOR,) && __GET_LOCATED(data__->GRIPPER2ONOUT,)) && __GET_LOCATED(data__->RIGHTCLAMPOUT,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,RIGHTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  if ((((__GET_LOCATED(data__->GRIPPER2ONSENSOR,) && !(__GET_LOCATED(data__->RIGHTPOS1CLAMPOFF,))) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,Z_AXIS2DOWNOUT,,__BOOL_LITERAL(FALSE));
  };
  if ((((__GET_LOCATED(data__->GRIPPER2ONSENSOR,) && !(__GET_LOCATED(data__->RIGHTPOS1CLAMPOFF,))) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_VAR(data__->,PICKUPFORSTACK,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG6.,CLK,,__GET_LOCATED(data__->Z_AXIS2DOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG6);
  if ((((((__GET_VAR(data__->F_TRIG6.Q,) && !(__GET_LOCATED(data__->Z_AXIS2DOWNOUT,))) && __GET_LOCATED(data__->GRIPPER2ONSENSOR,)) && __GET_LOCATED(data__->GRIPPER2ONOUT,)) && __GET_VAR(data__->PICKUPFORSTACK,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,X_AXIS2MOVEOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG7.,CLK,,__GET_LOCATED(data__->Z_AXIS2DOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG7);
  if ((((((__GET_VAR(data__->F_TRIG7.Q,) && !(__GET_LOCATED(data__->Z_AXIS2DOWNOUT,))) && __GET_LOCATED(data__->GRIPPER2ONSENSOR,)) && __GET_LOCATED(data__->GRIPPER2ONOUT,)) && __GET_VAR(data__->PICKUPFORSTACK,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_VAR(data__->,PICKUPFORSTACK,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG8.,CLK,,__GET_LOCATED(data__->Z_AXIS2DOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG8);
  if ((((((__GET_VAR(data__->F_TRIG8.Q,) && !(__GET_LOCATED(data__->Z_AXIS2DOWNOUT,))) && __GET_LOCATED(data__->GRIPPER2ONSENSOR,)) && __GET_LOCATED(data__->GRIPPER2ONOUT,)) && __GET_VAR(data__->PICKUPFORSTACK,)) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,RIGHTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG9.,CLK,,__GET_LOCATED(data__->X_AXIS2MOVESENSOR,));
  F_TRIG_body__(&data__->F_TRIG9);
  if ((((((__GET_VAR(data__->F_TRIG9.Q,) && !(__GET_LOCATED(data__->X_AXIS2MOVEOUT,))) && __GET_LOCATED(data__->GRIPPER2ONSENSOR,)) && __GET_LOCATED(data__->GRIPPER2ONOUT,)) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,Z_AXIS2DOWNOUT,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG10.,CLK,,__GET_LOCATED(data__->X_AXIS2MOVESENSOR,));
  F_TRIG_body__(&data__->F_TRIG10);
  if ((((((__GET_VAR(data__->F_TRIG10.Q,) && !(__GET_LOCATED(data__->X_AXIS2MOVEOUT,))) && __GET_LOCATED(data__->GRIPPER2ONSENSOR,)) && __GET_LOCATED(data__->GRIPPER2ONOUT,)) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_LOCATED(data__->LEFTCLAMPOUT,))) {
    __SET_LOCATED(data__->,LEFTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG11.,CLK,,__GET_LOCATED(data__->Z_AXIS2DOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG11);
  if ((((((__GET_VAR(data__->F_TRIG11.Q,) && __GET_LOCATED(data__->Z_AXIS2DOWNOUT,)) && !(__GET_LOCATED(data__->X_AXIS2MOVEOUT,))) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_VAR(data__->BEGINASSEMBLY,)) && !(__GET_LOCATED(data__->LEFTCLAMPOUT,)))) {
    __SET_LOCATED(data__->,GRIPPER2ONOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG12.,CLK,,__GET_LOCATED(data__->Z_AXIS2DOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG12);
  if ((((((__GET_VAR(data__->F_TRIG12.Q,) && __GET_LOCATED(data__->Z_AXIS2DOWNOUT,)) && !(__GET_LOCATED(data__->X_AXIS2MOVEOUT,))) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_VAR(data__->BEGINASSEMBLY,)) && !(__GET_LOCATED(data__->LEFTCLAMPOUT,)))) {
    __SET_LOCATED(data__->,Z_AXIS2DOWNOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG13.,CLK,,__GET_LOCATED(data__->Z_AXIS2DOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG13);
  if ((((((__GET_VAR(data__->F_TRIG13.Q,) && __GET_LOCATED(data__->Z_AXIS2DOWNOUT,)) && !(__GET_LOCATED(data__->X_AXIS2MOVEOUT,))) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_VAR(data__->BEGINASSEMBLY,)) && !(__GET_LOCATED(data__->LEFTCLAMPOUT,)))) {
    __SET_LOCATED(data__->,X_AXIS2MOVEOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG14.,CLK,,__GET_LOCATED(data__->Z_AXIS2DOWNSENSOR,));
  F_TRIG_body__(&data__->F_TRIG14);
  if ((((((!(__GET_LOCATED(data__->GRIPPER2ONOUT,)) && __GET_VAR(data__->F_TRIG14.Q,)) && !(__GET_LOCATED(data__->Z_AXIS2DOWNOUT,))) && !(__GET_LOCATED(data__->X_AXIS2MOVEOUT,))) && !(__GET_LOCATED(data__->RIGHTCLAMPOUT,))) && __GET_VAR(data__->BEGINASSEMBLY,))) {
    __SET_LOCATED(data__->,LEFTPOS4_RAISE,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->F_TRIG15.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR6,));
  F_TRIG_body__(&data__->F_TRIG15);
  if (((__GET_VAR(data__->F_TRIG15.Q,) && __GET_LOCATED(data__->LEFTPOS4_RAISE,)) || !(__GET_EXTERNAL(data__->FACTORYIORUNNING,)))) {
    __SET_LOCATED(data__->,Z_AXIS2DOWNOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG16.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR6,));
  F_TRIG_body__(&data__->F_TRIG16);
  if ((__GET_VAR(data__->F_TRIG16.Q,) && __GET_LOCATED(data__->LEFTPOS4_RAISE,))) {
    __SET_LOCATED(data__->,X_AXIS2MOVEOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG17.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR6,));
  F_TRIG_body__(&data__->F_TRIG17);
  if ((__GET_VAR(data__->F_TRIG17.Q,) && __GET_LOCATED(data__->LEFTPOS4_RAISE,))) {
    __SET_LOCATED(data__->,RIGHTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_LOCATED(data__->,STACKEMITTER,,__GET_LOCATED(data__->CONV6M_2_STACKFEEDER,));
  __SET_VAR(data__->F_TRIG18.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR6,));
  F_TRIG_body__(&data__->F_TRIG18);
  if ((__GET_VAR(data__->F_TRIG18.Q,) && __GET_LOCATED(data__->LEFTPOS4_RAISE,))) {
    __SET_LOCATED(data__->,GRIPPER2ONOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG19.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR6,));
  F_TRIG_body__(&data__->F_TRIG19);
  if ((__GET_VAR(data__->F_TRIG19.Q,) && __GET_LOCATED(data__->LEFTPOS4_RAISE,))) {
    __SET_LOCATED(data__->,LEFTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG20.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR6,));
  F_TRIG_body__(&data__->F_TRIG20);
  if ((__GET_VAR(data__->F_TRIG20.Q,) && __GET_LOCATED(data__->LEFTPOS4_RAISE,))) {
    __SET_VAR(data__->,BEGINASSEMBLY,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG21.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR6,));
  F_TRIG_body__(&data__->F_TRIG21);
  if ((__GET_VAR(data__->F_TRIG21.Q,) && __GET_LOCATED(data__->LEFTPOS4_RAISE,))) {
    __SET_LOCATED(data__->,LEFTPOS4_RAISE,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->F_TRIG22.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR5,));
  F_TRIG_body__(&data__->F_TRIG22);
  if ((__GET_VAR(data__->F_TRIG22.Q,) && __GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_VAR(data__->,STOPFEEDERCONVEYOR,,__BOOL_LITERAL(TRUE));
  };
  __SET_VAR(data__->R_TRIG1.,CLK,,__GET_LOCATED(data__->LEFTPOS4_RAISE,));
  R_TRIG_body__(&data__->R_TRIG1);
  if (((__GET_VAR(data__->R_TRIG1.Q,) && __GET_EXTERNAL(data__->FACTORYIORUNNING,)) || !(__GET_EXTERNAL(data__->FACTORYIORUNNING,)))) {
    __SET_VAR(data__->,STOPFEEDERCONVEYOR,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,Z_AXIS2DOWNOUT,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,X_AXIS2MOVEOUT,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,RIGHTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,GRIPPER2ONOUT,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,LEFTCLAMPOUT,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_VAR(data__->,BEGINASSEMBLY,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_LOCATED(data__->,LEFTPOS4_RAISE,,__BOOL_LITERAL(FALSE));
  };
  if (!(__GET_EXTERNAL(data__->FACTORYIORUNNING,))) {
    __SET_VAR(data__->,PICKUPFORSTACK,,__BOOL_LITERAL(FALSE));
  };
  __SET_VAR(data__->R_TRIG2.,CLK,,__GET_LOCATED(data__->DIFFUSESENSOR6,));
  R_TRIG_body__(&data__->R_TRIG2);
  __SET_VAR(data__->CTU0.,CU,,__GET_VAR(data__->R_TRIG2.Q,));
  __SET_VAR(data__->CTU0.,R,,!(__GET_EXTERNAL(data__->FACTORYIORUNNING,)));
  __SET_VAR(data__->CTU0.,PV,,100);
  CTU_body__(&data__->CTU0);
  __SET_LOCATED(data__->,CRATEDPRODUCTCOUNT,,__GET_VAR(data__->CTU0.CV,));

  goto __end;

__end:
  return;
} // PALLETIZER_body__() 





