void TANK_AUTO_init__(TANK_AUTO *data__, BOOL retain) {
  __INIT_LOCATED(BOOL,__IX100_0,data__->I_PBFILL,retain)
  __INIT_LOCATED_VALUE(data__->I_PBFILL,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__IX100_1,data__->I_PBDISCHARGE,retain)
  __INIT_LOCATED_VALUE(data__->I_PBDISCHARGE,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(INT,__IW100,data__->I_LEVEL_METER,retain)
  __INIT_LOCATED_VALUE(data__->I_LEVEL_METER,0)
  __INIT_LOCATED(BOOL,__IX100_2,data__->I_MODESELECTOR,retain)
  __INIT_LOCATED_VALUE(data__->I_MODESELECTOR,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(INT,__QW101,data__->Q_FILL_VALVE,retain)
  __INIT_LOCATED_VALUE(data__->Q_FILL_VALVE,0)
  __INIT_LOCATED(INT,__QW102,data__->Q_DISCHARGE_VALVE,retain)
  __INIT_LOCATED_VALUE(data__->Q_DISCHARGE_VALVE,0)
  __INIT_LOCATED(INT,__QW100,data__->Q_DISPLAY,retain)
  __INIT_LOCATED_VALUE(data__->Q_DISPLAY,0)
  __INIT_LOCATED(BOOL,__QX100_0,data__->Q_FILL_LIGHT,retain)
  __INIT_LOCATED_VALUE(data__->Q_FILL_LIGHT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(BOOL,__QX100_2,data__->Q_DISCHARGE_LIGHT,retain)
  __INIT_LOCATED_VALUE(data__->Q_DISCHARGE_LIGHT,__BOOL_LITERAL(FALSE))
  __INIT_LOCATED(INT,__MW1,data__->LOWSETPOINT,retain)
  __INIT_LOCATED_VALUE(data__->LOWSETPOINT,2)
  __INIT_LOCATED(INT,__MW2,data__->HIGHSETPOINT,retain)
  __INIT_LOCATED_VALUE(data__->HIGHSETPOINT,8)
  __INIT_LOCATED(INT,__MW0,data__->TANKLEVEL,retain)
  __INIT_LOCATED_VALUE(data__->TANKLEVEL,0)
}

// Code part
void TANK_AUTO_body__(TANK_AUTO *data__) {
  // Initialise TEMP variables

  __SET_LOCATED(data__->,TANKLEVEL,,__GET_LOCATED(data__->I_LEVEL_METER,));
  if ((__GET_LOCATED(data__->I_MODESELECTOR,) == __BOOL_LITERAL(FALSE))) {
    if (((__GET_LOCATED(data__->I_PBFILL,) == __BOOL_LITERAL(TRUE)) && ((__GET_LOCATED(data__->TANKLEVEL,) < __GET_LOCATED(data__->LOWSETPOINT,)) || (__GET_LOCATED(data__->TANKLEVEL,) <= __GET_LOCATED(data__->HIGHSETPOINT,))))) {
      __SET_LOCATED(data__->,Q_FILL_VALVE,,10);
      __SET_LOCATED(data__->,Q_FILL_LIGHT,,__BOOL_LITERAL(TRUE));
    } else {
      __SET_LOCATED(data__->,Q_FILL_VALVE,,0);
      __SET_LOCATED(data__->,Q_FILL_LIGHT,,__BOOL_LITERAL(FALSE));
    };
    if (((__GET_LOCATED(data__->I_PBDISCHARGE,) == __BOOL_LITERAL(FALSE)) && (__GET_LOCATED(data__->TANKLEVEL,) >= __GET_LOCATED(data__->HIGHSETPOINT,)))) {
      __SET_LOCATED(data__->,Q_DISCHARGE_VALVE,,10);
      __SET_LOCATED(data__->,Q_DISCHARGE_LIGHT,,__BOOL_LITERAL(TRUE));
    } else {
      __SET_LOCATED(data__->,Q_DISCHARGE_VALVE,,0);
      __SET_LOCATED(data__->,Q_DISCHARGE_LIGHT,,__BOOL_LITERAL(FALSE));
    };
  };
  if ((__GET_LOCATED(data__->I_MODESELECTOR,) == __BOOL_LITERAL(TRUE))) {
    if (((__GET_LOCATED(data__->TANKLEVEL,) < __GET_LOCATED(data__->LOWSETPOINT,)) || ((__GET_LOCATED(data__->TANKLEVEL,) >= __GET_LOCATED(data__->LOWSETPOINT,)) && (__GET_LOCATED(data__->TANKLEVEL,) < __GET_LOCATED(data__->HIGHSETPOINT,))))) {
      __SET_LOCATED(data__->,Q_FILL_VALVE,,7);
      __SET_LOCATED(data__->,Q_FILL_LIGHT,,__BOOL_LITERAL(TRUE));
    } else if ((__GET_LOCATED(data__->TANKLEVEL,) >= __GET_LOCATED(data__->HIGHSETPOINT,))) {
      __SET_LOCATED(data__->,Q_FILL_VALVE,,0);
      __SET_LOCATED(data__->,Q_FILL_LIGHT,,__BOOL_LITERAL(FALSE));
    };
    if ((__GET_LOCATED(data__->TANKLEVEL,) >= __GET_LOCATED(data__->HIGHSETPOINT,))) {
      __SET_LOCATED(data__->,Q_DISCHARGE_VALVE,,5);
      __SET_LOCATED(data__->,Q_DISCHARGE_LIGHT,,__BOOL_LITERAL(TRUE));
    } else {
      __SET_LOCATED(data__->,Q_DISCHARGE_VALVE,,0);
      __SET_LOCATED(data__->,Q_DISCHARGE_LIGHT,,__BOOL_LITERAL(FALSE));
    };
  };
  __SET_LOCATED(data__->,Q_DISPLAY,,__GET_LOCATED(data__->I_LEVEL_METER,));

  goto __end;

__end:
  return;
} // TANK_AUTO_body__() 





