#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

// PROGRAM BASE_PRODUCTION
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,STOPBASEPRODUCTION)

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_LOCATED(BOOL,BASESENTRY)
  __DECLARE_LOCATED(BOOL,BASESEXIT)
  __DECLARE_EXTERNAL(BOOL,BASESCENTERBUSY)
  __DECLARE_EXTERNAL(BOOL,LIDSCENTERBUSY)
  __DECLARE_LOCATED(BOOL,BASESCENTERERROR)
  __DECLARE_LOCATED(BOOL,BASESCENTERSTOP)
  __DECLARE_LOCATED(BOOL,BASESCENTERSTART)
  __DECLARE_LOCATED(BOOL,BASESCENTERRESET)
  __DECLARE_LOCATED(BOOL,BASESRAWCONVEYOR)
  __DECLARE_LOCATED(BOOL,BASESEXITCONVEYOR)
  __DECLARE_LOCATED(BOOL,BASESEMITTER)
  __DECLARE_LOCATED(BOOL,BELTCONV5)
  __DECLARE_LOCATED(BOOL,BELTCONV6)
  __DECLARE_LOCATED(BOOL,EXITCONV)
  __DECLARE_EXTERNAL(BOOL,FACTORYIORUNNING)
  R_TRIG R_TRIG0;
  RS RS0;
  __DECLARE_LOCATED(INT,BASESEXITCOUNTER)
  CTU CTU0;
  __DECLARE_EXTERNAL(INT,SCADASETPRODUCTCOUNT)
  __DECLARE_EXTERNAL(INT,ASSEMBLEDPRODUCTCOUNT)
  __DECLARE_EXTERNAL(BOOL,ESTOPGLOBAL)
  R_TRIG R_TRIG1;
  __DECLARE_VAR(BOOL,LT37_OUT)

} BASE_PRODUCTION;

void BASE_PRODUCTION_init__(BASE_PRODUCTION *data__, BOOL retain);
// Code part
void BASE_PRODUCTION_body__(BASE_PRODUCTION *data__);
// PROGRAM ASSEMBLY
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_EXTERNAL(BOOL,FACTORYIORUNNING)
  __DECLARE_EXTERNAL(BOOL,ASSEMBLYESTOP2)
  __DECLARE_EXTERNAL(BOOL,ESTOPGLOBAL)
  __DECLARE_EXTERNAL(BOOL,ASSEMBLYSTARTPB3)
  __DECLARE_EXTERNAL(BOOL,ASSEMBLYRESETPB2)
  __DECLARE_VAR(BOOL,SCADASTOPLOCAL)
  __DECLARE_VAR(BOOL,SCADARESETLOCAL)
  __DECLARE_EXTERNAL(INT,SCADAESTOP)
  __DECLARE_EXTERNAL(INT,SCADAESTOPRESET)
  __DECLARE_LOCATED(BOOL,CONV6M_1_LIDFEEDER)
  __DECLARE_LOCATED(BOOL,CONV6M_4_BASEFEEDER0)
  __DECLARE_LOCATED(BOOL,DIFFUSESENSOR1)
  __DECLARE_LOCATED(BOOL,DIFFUSESENSOR3)
  __DECLARE_LOCATED(BOOL,LEFTCLAMPSENSOR)
  __DECLARE_LOCATED(BOOL,RIGHTCLAMPSENSOR)
  __DECLARE_LOCATED(BOOL,LEFTCLAMPOUT)
  __DECLARE_LOCATED(BOOL,RIGHTCLAMPOUT)
  __DECLARE_LOCATED(BOOL,Z_AXISDOWNOUT)
  __DECLARE_LOCATED(BOOL,X_AXISMOVEOUT)
  __DECLARE_LOCATED(BOOL,Z_AXISDOWNSENSOR)
  __DECLARE_LOCATED(BOOL,X_AXISMOVESENSOR)
  __DECLARE_LOCATED(BOOL,GRIPPERONOUT)
  __DECLARE_LOCATED(BOOL,CONV4M_5_AFTERRAISE)
  __DECLARE_LOCATED(BOOL,LEFTPOS2_RAISE)
  __DECLARE_LOCATED(BOOL,GRIPPERONSENSOR)
  __DECLARE_LOCATED(BOOL,DIFFUSESENSOR2)
  __DECLARE_VAR(BOOL,BEGINASSEMBLY)
  __DECLARE_VAR(BOOL,STOPBASEFEEDERCONV)
  __DECLARE_LOCATED(BOOL,DIFFUSESENSOR7)
  __DECLARE_LOCATED(WORD,VISIONSENSOR)
  __DECLARE_LOCATED(BOOL,PIVOTBELTRUN)
  __DECLARE_LOCATED(BOOL,PIVOTBELTTURN)
  __DECLARE_LOCATED(BOOL,REJECTIONALARM)
  __DECLARE_LOCATED(BOOL,REJECTIONSIREN)
  __DECLARE_VAR(BOOL,VISIONTESTFAIL1)
  __DECLARE_VAR(BOOL,VISIONTESTFAIL2)
  __DECLARE_VAR(BOOL,VISIONTESTFAIL)
  __DECLARE_VAR(BOOL,RUNREJECTIONPIVOT)
  TON TON0;
  __DECLARE_LOCATED(BOOL,BELTCONV6M_5)
  __DECLARE_LOCATED(BOOL,BELTCONV6M_6)
  __DECLARE_LOCATED(BOOL,BELTCONV6M_7)
  __DECLARE_LOCATED(BOOL,BELTCONV6M_8)
  __DECLARE_LOCATED(BOOL,CURVEBELTCONV1_CCW)
  __DECLARE_LOCATED(BOOL,ASSEMBLYREDLIGHT)
  __DECLARE_EXTERNAL(INT,ASSEMBLEDPRODUCTCOUNT)
  __DECLARE_EXTERNAL(INT,QCSTATIONENABLE)
  __DECLARE_LOCATED(BOOL,BOOLQCSTATIONENABLE)
  __DECLARE_LOCATED(INT,REJECTEDPRODUCTCOUNT)
  CTU CTU0;
  CTU CTU1;
  F_TRIG F_TRIG1;
  F_TRIG F_TRIG2;
  F_TRIG F_TRIG3;
  F_TRIG F_TRIG4;
  F_TRIG F_TRIG5;
  F_TRIG F_TRIG6;
  F_TRIG F_TRIG7;
  F_TRIG F_TRIG8;
  F_TRIG F_TRIG9;
  F_TRIG F_TRIG10;
  F_TRIG F_TRIG11;
  F_TRIG F_TRIG12;
  F_TRIG F_TRIG13;
  F_TRIG F_TRIG14;
  F_TRIG F_TRIG15;
  F_TRIG F_TRIG16;
  R_TRIG R_TRIG1;
  R_TRIG R_TRIG2;
  __DECLARE_VAR(BOOL,NE114_OUT)
  __DECLARE_VAR(BOOL,NE115_OUT)
  R_TRIG R_TRIG3;
  R_TRIG R_TRIG4;
  __DECLARE_VAR(BOOL,EQ203_OUT)
  __DECLARE_VAR(BOOL,EQ204_OUT)
  __DECLARE_VAR(BOOL,EQ217_OUT)

} ASSEMBLY;

void ASSEMBLY_init__(ASSEMBLY *data__, BOOL retain);
// Code part
void ASSEMBLY_body__(ASSEMBLY *data__);
// PROGRAM WAREHOUSE
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_LOCATED(BOOL,ROLLERCONV2M_1)
  __DECLARE_LOCATED(BOOL,ROLLERCONV2M_2)
  __DECLARE_LOCATED(BOOL,ROLLERCONV2M_3)
  __DECLARE_LOCATED(BOOL,ROLLERCONV2M_4)
  __DECLARE_LOCATED(BOOL,ROLLERCONV2M_5)
  __DECLARE_LOCATED(BOOL,CURVEROLLER2_CW)
  __DECLARE_LOCATED(BOOL,CURVEROLLER1_CCW)
  __DECLARE_LOCATED(BOOL,LOADCONV1)
  __DECLARE_LOCATED(BOOL,LOADCONV2)
  __DECLARE_LOCATED(BOOL,STACKCRANE1_LEFT)
  __DECLARE_LOCATED(BOOL,STACKCRANE1_RIGHT)
  __DECLARE_LOCATED(BOOL,STACKCRANE1_LIFT)
  __DECLARE_LOCATED(INT,STACKCRANE1_TARGETPOS)
  __DECLARE_LOCATED(BOOL,STACKCRANE1_MOVX)
  __DECLARE_LOCATED(BOOL,STACKCRANE1_MOVZ)
  __DECLARE_LOCATED(BOOL,STACKCRANE1_LEFTLIMIT)
  __DECLARE_LOCATED(BOOL,STACKCRANE1_RIGHTLIMIT0)
  __DECLARE_LOCATED(BOOL,STACKCRANE1_MIDDLELIMIT)
  __DECLARE_LOCATED(BOOL,REFLECTIVESENSOR_5)
  __DECLARE_LOCATED(BOOL,REFLECTIVESENSOR_6)
  __DECLARE_LOCATED(BOOL,REFLECTIVESENSOR_7)
  __DECLARE_LOCATED(BOOL,REFLECTIVESENSOR_8)
  __DECLARE_EXTERNAL(BOOL,FACTORYIORUNNING)
  __DECLARE_VAR(BOOL,STARTLOADING)
  __DECLARE_VAR(BOOL,STARTSTACKING)
  __DECLARE_VAR(BOOL,STARTSTACKING2)
  __DECLARE_VAR(BOOL,STARTSTACKING3)
  __DECLARE_VAR(BOOL,STARTSTACKING4)
  __DECLARE_VAR(BOOL,STARTSTACKING5)
  __DECLARE_VAR(BOOL,STARTSTACKING6)
  __DECLARE_VAR(BOOL,STARTSTACKING7)
  __DECLARE_VAR(BOOL,STARTSTACKING8)
  __DECLARE_VAR(BOOL,FACTORYIOSTOP)
  __DECLARE_LOCATED(BOOL,SAFETYDOORSENSOR)
  __DECLARE_LOCATED(BOOL,SAFETYDOORRESET)
  __DECLARE_LOCATED(BOOL,SAFETYDOORLIGHT)
  __DECLARE_LOCATED(BOOL,SAFETYDOORSIREN)
  __DECLARE_VAR(INT,TARGETPOSITIONVAR)
  CTU CTU0;
  F_TRIG F_TRIG1;
  F_TRIG F_TRIG2;
  F_TRIG F_TRIG3;
  R_TRIG R_TRIG1;
  __DECLARE_VAR(INT,SEL60_OUT)
  R_TRIG R_TRIG2;
  F_TRIG F_TRIG4;
  F_TRIG F_TRIG5;
  R_TRIG R_TRIG3;
  F_TRIG F_TRIG6;
  R_TRIG R_TRIG4;
  __DECLARE_VAR(BOOL,MOVE109_ENO)
  __DECLARE_VAR(INT,MOVE109_OUT)

} WAREHOUSE;

void WAREHOUSE_init__(WAREHOUSE *data__, BOOL retain);
// Code part
void WAREHOUSE_body__(WAREHOUSE *data__);
// PROGRAM LIDS_PRODUCTION
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,STOPLIDPRODUCTION)

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_LOCATED(BOOL,LIDSENTRY)
  __DECLARE_LOCATED(BOOL,LIDSEXIT)
  __DECLARE_EXTERNAL(BOOL,LIDSCENTERBUSY)
  __DECLARE_EXTERNAL(BOOL,BASESCENTERBUSY)
  __DECLARE_LOCATED(BOOL,LIDSCENTERERROR)
  __DECLARE_LOCATED(BOOL,LIDSCENTERSTOP)
  __DECLARE_LOCATED(BOOL,LIDSCENTERSTART)
  __DECLARE_LOCATED(BOOL,LIDSCENTERPRODUCE)
  __DECLARE_LOCATED(BOOL,LIDSRAWCONVEYOR)
  __DECLARE_LOCATED(BOOL,LIDSEXITCONVEYOR)
  __DECLARE_LOCATED(BOOL,LIDSEXITCONVEYOR2)
  __DECLARE_LOCATED(BOOL,LIDSEMITTER)
  __DECLARE_EXTERNAL(BOOL,FACTORYIORUN)
  __DECLARE_EXTERNAL(BOOL,FACTORYIORUNNING)
  R_TRIG R_TRIG0;
  RS RS0;
  CTU CTU0;
  __DECLARE_LOCATED(INT,LIDSEXITCOUNTER)
  __DECLARE_LOCATED(BOOL,STARTBUTTON2)
  __DECLARE_EXTERNAL(INT,SCADASETPRODUCTCOUNT)
  __DECLARE_EXTERNAL(INT,ASSEMBLEDPRODUCTCOUNT)
  __DECLARE_EXTERNAL(INT,SCADAFACTORYIOSTART)
  __DECLARE_EXTERNAL(BOOL,ESTOPGLOBAL)
  R_TRIG R_TRIG1;
  __DECLARE_VAR(BOOL,LT37_OUT)
  __DECLARE_VAR(BOOL,EQ43_OUT)

} LIDS_PRODUCTION;

void LIDS_PRODUCTION_init__(LIDS_PRODUCTION *data__, BOOL retain);
// Code part
void LIDS_PRODUCTION_body__(LIDS_PRODUCTION *data__);
// PROGRAM PALLETIZER
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_EXTERNAL(BOOL,FACTORYIORUNNING)
  __DECLARE_LOCATED(BOOL,CONV6M_2_STACKFEEDER)
  __DECLARE_LOCATED(BOOL,CONV6M_3_AFTERSTACK)
  __DECLARE_LOCATED(BOOL,DIFFUSESENSOR5)
  __DECLARE_LOCATED(BOOL,DIFFUSESENSOR4)
  __DECLARE_LOCATED(BOOL,LEFTCLAMPSENSOR)
  __DECLARE_LOCATED(BOOL,RIGHTCLAMPSENSOR)
  __DECLARE_LOCATED(BOOL,LEFTCLAMPOUT)
  __DECLARE_LOCATED(BOOL,RIGHTCLAMPOUT)
  __DECLARE_LOCATED(BOOL,Z_AXIS2DOWNOUT)
  __DECLARE_LOCATED(BOOL,X_AXIS2MOVEOUT)
  __DECLARE_LOCATED(BOOL,Z_AXIS2DOWNSENSOR)
  __DECLARE_LOCATED(BOOL,X_AXIS2MOVESENSOR)
  __DECLARE_LOCATED(BOOL,GRIPPER2ONOUT)
  __DECLARE_LOCATED(BOOL,LEFTPOS4_RAISE)
  __DECLARE_LOCATED(BOOL,STACKEMITTER)
  __DECLARE_LOCATED(BOOL,GRIPPER2ONSENSOR)
  __DECLARE_LOCATED(BOOL,DIFFUSESENSOR6)
  __DECLARE_LOCATED(BOOL,RIGHTPOS1CLAMPOFF)
  __DECLARE_VAR(BOOL,BEGINASSEMBLY)
  __DECLARE_VAR(BOOL,STOPFEEDERCONVEYOR)
  __DECLARE_VAR(BOOL,PICKUPFORSTACK)
  CTU CTU0;
  __DECLARE_LOCATED(INT,CRATEDPRODUCTCOUNT)
  F_TRIG F_TRIG1;
  F_TRIG F_TRIG2;
  F_TRIG F_TRIG3;
  F_TRIG F_TRIG4;
  F_TRIG F_TRIG5;
  F_TRIG F_TRIG6;
  F_TRIG F_TRIG7;
  F_TRIG F_TRIG8;
  F_TRIG F_TRIG9;
  F_TRIG F_TRIG10;
  F_TRIG F_TRIG11;
  F_TRIG F_TRIG12;
  F_TRIG F_TRIG13;
  F_TRIG F_TRIG14;
  F_TRIG F_TRIG15;
  F_TRIG F_TRIG16;
  F_TRIG F_TRIG17;
  F_TRIG F_TRIG18;
  F_TRIG F_TRIG19;
  F_TRIG F_TRIG20;
  F_TRIG F_TRIG21;
  F_TRIG F_TRIG22;
  R_TRIG R_TRIG1;
  R_TRIG R_TRIG2;

} PALLETIZER;

void PALLETIZER_init__(PALLETIZER *data__, BOOL retain);
// Code part
void PALLETIZER_body__(PALLETIZER *data__);
#endif //__POUS_H
